# Generated by Django 4.0.2 on 2022-02-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Wallet',
        ),
    ]
